/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./app/views/**/*.html.erb",
        "./app/helpers/**/*.rb",
        "./app/javascript/**/*.js",
        "./app/components/**/*.erb",
        "./app/assets/stylesheets/**/*.css"
    ],
    safelist: [
        // Example: add all dynamic colors or classes here
        'bg-red-500',
        'bg-green-500',
        'bg-blue-500',
        'text-red-500',
        'text-green-500',
        'text-blue-500',
        'hover:bg-red-500',
        'hover:bg-green-500',
        'hover:bg-blue-500',
        'text-white',
        'text-black',
        // Custom and dynamic classes from ERB files
        'bg-gradient-to-br',
        'from-pink-400',
        'to-pink-500',
        'from-blue-400',
        'to-purple-500',
        'from-yellow-300',
        'to-orange-400',
        'from-[#ff9b9f]',
        'to-[#fd79a8]',
        'bg-[#fef8f9]',
        'bg-[#f5f0f1]',
        'border-[#fef8f9]',
        'border-[#F9DCDD]',
        'bg-[#E5D6F0]',
        'bg-purple-200',
        'text-purple-700',
        'hover:bg-purple-300',
        'bg-red-100',
        'text-red-600',
        'hover:bg-red-200',
        'bg-pink-100',
        'text-pink-700',
        'bg-purple-100',
        'text-purple-700',
        'bg-indigo-100',
        'text-indigo-500',
        'bg-yellow-100',
        'text-yellow-500',
        'bg-gradient-to-r',
        'from-pink-400',
        'to-pink-500',
        'hover:from-pink-500',
        'hover:to-pink-600',
        'bg-muted',
        'text-muted-foreground',
        'bg-secondary',
        'text-secondary-foreground',
        'hover:bg-gray-50',
        'hover:shadow-md',
        'hover:scale-[1.02]',
        'active:scale-[0.98]',
        'min-w-[90px]',
        'min-h-[36px]',
        'focus:ring-primary',
        'hover:border-[#ff9b9f]',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}
